### ISSUE TITLE
ResNet50 Batch Normalization Mode

### ISSUE THREAD

**Issue by jmhessel** [fchollet/deep-learning-models#2]
Would it be reasonable to add an optional batch normalization mode argument to ResNet50? Allowing for mode = 2 would enable ResNet50 to be used in a shared fashion. I think the same BN initializations could be used in mode = 2. Happy to do a PR if folks think it's worthwhile.

**Comment by jmhessel** [comment]
(created a quick PR -- #3)

**Comment by fchollet** [comment]
> Allowing for mode = 2 would enable ResNet50 to be used in a shared fashion.

It the future I expect it will be possible to share regular BN layers.

**Comment by jmhessel** [comment]
Gotcha -- I didn't realize that mode=2 was potentially becoming deprecated.
