### ISSUE TITLE
KeyError: “Can’t open attribute (Can’t locate attribute: ‘layer_names’)

### ISSUE THREAD

**Issue by lightwolfz** [fchollet/deep-learning-models#55]
I tried to run this code

```
from vgg16 import VGG16
from keras.preprocessing import image
from imagenet_utils import preprocess_input

model = VGG16(weights='imagenet', include_top=False)

img_path = 'elephant.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

features = model.predict(x)
```

but i got KeyError: “Can’t open attribute (Can’t locate attribute: ‘layer_names’)
what should i do?

**Comment by luntai** [comment]
I meet this too.

**Comment by muzi-8** [comment]
I think you download the error file;
you maybe try download the weights files here 
(https://github.com/fchollet/deep-learning-models/releases)
you can try ~good luck!

**Comment by lightwolfz** [comment]
It went good , thank you very much :D
