### ISSUE TITLE
Inception-v3 fine-tuning

### ISSUE THREAD

**Issue by nournia** [fchollet/deep-learning-models#8]
Hi,
Is it possible to use provided weights for fine-tuning `inception-v3` model?
Writing a simple manual for this, really helps. Something like [Fine-tuning CaffeNet for Style Recognition](http://caffe.berkeleyvision.org/gathered/examples/finetune_flickr_style.html).

**Comment by fchollet** [comment]
See this example: [Inception v3 fine-tuning on new data with new classes](https://keras.io/applications/#fine-tune-inceptionv3-on-a-new-set-of-classes)

**Comment by nournia** [comment]
Thanks.

**Comment by danielvarga** [comment]
@nournia @fchollet That example code is awesome, and I've just turned it into a fully functional application:

https://github.com/danielvarga/keras-finetuning

Work in progress, especially the documentation, but I've already trained very accurate models with it, with just a few hundred examples per class.

**Comment by xiaodi68** [comment]
Very good example. Very helpful. @danielvarga 
One question. Inception V3 uses BGR image format. Do we need to convert the images from RGB format (scipy.misc.imread) to BGR format? I haven't seen this conversion in the codes.
Thanks.
